# Generated by Django 3.1.1 on 2020-10-15 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0008_delete_cartitem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
