# Generated by Django 3.1.1 on 2020-10-03 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Promotions',
        ),
    ]
