"""
Django settings for store project.

Generated by 'django-admin startproject' using Django 2.2.12.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
temp_dir=os.path.join(BASE_DIR, 'template')
static_dir=os.path.join(BASE_DIR, 'static')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'wutkozw$a-h+p#&07nwdt#f*w7=z_+0-4bxvhs^-dptrw9x&eb'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'productapp',
    'userapp',
    'coupon',
    'employee',
    'attendence',
    'payroll',
    'partner',
    'promotions',
    'customer',
    'rest_framework',
    'django_filters',
    'rest_framework.authtoken',
    'django_rest_passwordreset',
    'kronos',
  

]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'store.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [temp_dir],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'store.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
       'rest_framework.authentication.TokenAuthentication',

       'rest_framework_simplejwt.authentication.JWTAuthentication',

    ]
    }


STRIPE_PUBLISHABLE_KEY= 'pk_test_51HdsLZKTfVLaT0bRsSES7bTWFKdF1i7pKesh199v0BiWj7QcmN6g63HO9vuDrqGgNuOZZyqHS1hSfo65Gl1YIDiO005xaLyWvM'
STRIPE_SECRET_KEY='sk_test_51HdsLZKTfVLaT0bRnB15wd0E5BdNUvzbQuvnQPbZGTPfF6TtpXj9v3rdflsUJ8XCsPdQIvLkBX8xtoIXGmQIXUhe0055vq7sJj'
# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True
LOGIN_URL = '/login/'

LOGIN_REDIRECT_URL= "user_dashboard"

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS=[
static_dir,
]
CELERY_BROKER_URL='redis://127.0.0.1:6379/0'
CELERY_ACCEPT_CONTENT=['json']
CELERY_TASK_SERIALIZER='json'

EMAIL_HOST= 'smtp.gmail.com'
EMAIL_PORT= 587
EMAIL_HOST_USER= 'roshidubey2602@gmail.com'
EMAIL_HOST_PASSWORD='vandanaroshi2602'
EMAIL_USE_TLS= True


EMAIL_BACKEND= 'django.core.mail.backends.smtp.EmailBackend' 