# Generated by Django 2.2.12 on 2020-09-21 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Partner_RegistrationModel',
        ),
    ]
