# Generated by Django 2.2.12 on 2020-09-16 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.CharField(blank=True, max_length=200, null=True)),
                ('price', models.IntegerField()),
                ('quality', models.IntegerField()),
                ('issue_by', models.CharField(blank=True, max_length=200, null=True)),
                ('issue_to', models.CharField(blank=True, max_length=200, null=True)),
                ('last_updated', models.DateField(auto_now_add=True)),
                ('brand', models.CharField(blank=True, max_length=200, null=True)),
                ('quantity', models.IntegerField()),
                ('coupon', models.CharField(blank=True, max_length=200, null=True)),
                ('discount', models.IntegerField()),
            ],
        ),
    ]
