# Generated by Django 3.1.1 on 2020-09-30 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='phone_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
