# Generated by Django 3.1.1 on 2020-09-30 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0002_auto_20200930_0730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='partner',
            name='modified_at',
            field=models.DateField(auto_now=True),
        ),
    ]
